In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
import time

In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("Vectorized version:" + str(1000*(toc-tic)) + "ms")


Vectorized version:1.184225082397461ms


In [11]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0 
tic = time.time()
for i in range(1000000):
  c += a[i]*b[i]
toc = time.time()

print(c)
print("fOR loop:" + str(1000*(toc-tic)) + "ms")

250364.23710468723
Vectorized version:4.837274551391602ms
250364.23710469747
fOR loop:716.353178024292ms




---


**Broadcasting in Python**









Calories from CarbsiProteins,Fats in 100g of differed foods:

In [12]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [13]:
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [15]:
percentage = 100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

A Note on Python/Numpy Vectors

In [18]:
a = np.random.randn(5)
a

array([ 0.02311871, -0.54730493, -0.18109   , -0.21914135,  0.01425169])

In [19]:
a.shape

(5,)

In [20]:
a.T

array([ 0.02311871, -0.54730493, -0.18109   , -0.21914135,  0.01425169])

In [21]:
np.dot(a,a.T)

0.38109679313215766

In [22]:
a = np.random.randn(5,1)
a

array([[-1.74528167],
       [-0.65670061],
       [ 0.23395027],
       [ 1.63651443],
       [-2.03842855]])

In [23]:
a.T

array([[-1.74528167, -0.65670061,  0.23395027,  1.63651443, -2.03842855]])